apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bkarakas-memory-demo
  name: bkarakas-memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
{{ toYaml .Values.extra_packages.env | indent 4 }}