apiVersion: v1
kind: Pod
metadata:
  labels:
    app: azizasalieva95
  name: azizasalieva95
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: MESSAGE
      value: "Hey Whatsup"