apiVersion: v1
kind: Service
metadata:
  labels:
    app: Mahsuda-memory-demo
  name: Mahsuda-memory-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: Mahsuda-memory-demo
  type: ClusterIP





