apiVersion: v1
kind: Service
metadata:
  name: seedoffd-memory-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: seedoffd-memory-demo
  type: ClusterIP