dependencies:
- name: elasticsearch
  version: ^1.22.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
- name: kibana
  version: ^3.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kibana.enabled
- name: filebeat
  version: ^1.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: filebeat.enabled
- name: logstash
  version: ^1.6.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: logstash.enabled
