apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: fsadykov-memory-demo
  name: fsadykov-memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP