apiVersion: v1
kind: Service
metadata:
  name: ktalant-memory-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: ktalant-memory-demo
  type: ClusterIP