  
apiVersion: v1
kind: Pod
metadata:
  name: mkarimi20-memory-demo
  labels:
    app: mkarimi20-memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
{{ toYaml .Values.extra_packages.env | indent 4 }}