apiVersion: v1
kind: Service
metadata:
  labels:
  app: ulan-memory-demo
  name: ulan-memory-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: ulan-memory-demo
  type: ClusterIP
