apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: alisahp-memory-demo
  name: alisahp-memory-demo
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: MESSAGE
      value: "Hello World"
{{ toYaml .Values.extra_packages.env | indent 4 }}
    