apiVersion: v1
kind: Service
metadata:
  name: natan1988-memory-demo
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: natan1988-memory-demo
  type: ClusterIP
