# apiVersion: v1
# kind: Service
# metadata:
#   name: csamatov96-memory-demo #
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: http
#   selector:
#     app: csamatov96-memory-demo #
#   type: ClusterIP