apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: dhujaev5-memory-demo
  name: dhujaev5-memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: MESSAGE
      value: "Hello World"