apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: mahsuda-hello-world
  name: mahsuda-hello-world
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: MESSAGE
      value: "Hello World"