apiVersion: v1
kind: Service
metadata:
  name: mahsuda-hello-world
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: mahsuda-hello-world
  type: ClusterIP