name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Downloading  the helm binary script 
      run: |
        ## Downloading and putting home directory
        echo "Downloading helm command"
        sudo curl https://get.helm.sh/helm-v2.11.0-linux-amd64.tar.gz -o ~/helm.gz
        
        
        ## untaring the helm command 
        echo "Unarchiving helm packages"
        tar -zxvf ~/helm.gz
        
        ## copy to right place 
        ./linux-amd64/helm version --client
